fixes for arguments

diff --git a/kubectl-view-utilization b/kubectl-view-utilization
--- a/kubectl-view-utilization
+++ b/kubectl-view-utilization
@@ -155,7 +155,7 @@ cluster_utilization() {
 
         if ( output == "text") {
             req_cpu_text=prettify(req_cpu, cpu_pretty(req_cpu))
-            req_mem_text=prettify(req_mem, mem_pretty(req_mem))
+            req_mem_text=prettify(sprintf("%.0f",req_mem), mem_pretty(req_mem))
             req_header=prettify("Requests", "Req")
             req_width=calc_max_width(req_header, req_cpu_text, req_mem_text)
 
@@ -175,17 +175,17 @@ cluster_utilization() {
             percent_lim_width=calc_max_width(percent_lim_header, percent_lim_cpu_text, percent_lim_mem_text)
 
             alloc_cpu_text=prettify(alloc_cpu, cpu_pretty(alloc_cpu))
-            alloc_mem_text=prettify(alloc_mem, mem_pretty(alloc_mem))
+            alloc_mem_text=prettify(sprintf("%.0f", alloc_mem), mem_pretty(alloc_mem))
             alloc_header=prettify("Allocatable", "Alloc")
             alloc_width=calc_max_width(alloc_header, alloc_cpu_text, alloc_mem_text)
 
             sched_cpu_text=prettify(calc_sched(req_cpu, alloc_cpu), cpu_pretty(calc_sched(req_cpu, alloc_cpu)))
-            sched_mem_text=prettify(calc_sched(req_mem, alloc_mem), mem_pretty(calc_sched(req_mem, alloc_mem)))
+            sched_mem_text=prettify(sprintf("%.0f", calc_sched(req_mem, alloc_mem)), mem_pretty(calc_sched(req_mem, alloc_mem)))
             sched_header=prettify("Schedulable", "Sched")
             sched_width=calc_max_width(sched_header, sched_cpu_text, sched_mem_text)
 
             free_cpu_text=prettify(calc_free(req_cpu, lim_cpu, alloc_cpu), cpu_pretty(calc_free(req_cpu, lim_cpu, alloc_cpu)))
-            free_mem_text=prettify(calc_free(req_mem, lim_mem, alloc_mem), mem_pretty(calc_free(req_mem, lim_mem, alloc_mem)))
+            free_mem_text=prettify(sprintf("%.0f", calc_free(req_mem, lim_mem, alloc_mem)), mem_pretty(calc_free(req_mem, lim_mem, alloc_mem)))
             free_width=calc_max_width("Free", free_cpu_text, free_mem_text)
 
             printf("%-8s  %"req_width"s  %"percent_req_width"s  %"lim_width"s  %"percent_lim_width"s  %"alloc_width"s  %"sched_width"s  %"free_width"s\n", "Resource", req_header, percent_req_header, lim_header, percent_lim_header, alloc_header, sched_header, "Free");
@@ -332,7 +332,7 @@ function calc_max_width(a, b ,c) {
 
 function calc_sched(requests, allocatable) {
     if ( allocatable>= requests ) {
-        return (allocatable- requests)
+        return (allocatable - requests)
     } else {
         return 0
     }
@@ -388,117 +388,76 @@ function mem_pretty(sum){
 }
 '
 
-
-
-if [ "${1}" == "namespaces" ]; then
-    VIEW_UTILIZATION_SUBCOMMAND="namespaces"
-    shift;
-fi
-
-optspec=":nlohv-:"
-while getopts "$optspec" optchar; do
-    case "${optchar}" in
-        -)
-            case "${OPTARG}" in
-                help)
-                    print_help
-                    ;;
-                namespace)
-                    val="${!OPTIND}"; OPTIND=$(( OPTIND + 1 ))
-                    if [[ "${val}" != "" ]]; then
-                        VIEW_UTILIZATION_NAMESPACE="${val}"
-                    else 
-                        echo "no namespace specified"
-                        exit 1
-                    fi
-                    ;;
-                namespace=*)
-                    val=${OPTARG#*=}
-                    if [[ "${val}" != "" ]]; then
-                        VIEW_UTILIZATION_NAMESPACE="${val}"
-                    else 
-                        echo "no namespace specified"
-                        exit 1
-                    fi
-                    ;;
-                selector)
-                    val="${!OPTIND}"; OPTIND=$(( OPTIND + 1 ))
-                    VIEW_UTILIZATION_NODE_LABEL="${val}"
-                    ;;
-                selector=*)
-                    val=${OPTARG#*=}
-                    VIEW_UTILIZATION_NODE_LABEL="${val}"
-                    ;;
-                output)
-                    val="${!OPTIND}"; OPTIND=$(( OPTIND + 1 ))
-                    if [[ "${val}" == "text" ]] || [[ "${val}" == "json" ]]; then
-                        VIEW_UTILIZATION_OUTPUT=$val
-                    else
-                        echo "valid values are text, json"
-                        exit 1
-                    fi
-                    ;;
-                output=*)
-                    val=${OPTARG#*=}
-                    if [[ "${val}" == "text" ]] || [[ "${val}" == "json" ]]; then
-                        VIEW_UTILIZATION_OUTPUT=$val
-                    else
-                        echo "valid values are text, json"
-                        exit 1
-                    fi
-                    ;;
-                *)
-                    echo "Unknown option --${OPTARG}" >&2
-                    exit 1
-                    ;;
-            esac;;
-        n)
-            shift
-            if test $# -gt 0; then
-                VIEW_UTILIZATION_NAMESPACE=$1
-            else
-                echo "no namespace specified"
+while [ "$#" -gt 0 ]; do
+    case "$1" in
+        namespaces) VIEW_UTILIZATION_SUBCOMMAND="namespaces"; shift;;
+        -n|--namespace)
+            if [[ $# -lt 2 ]]; then
+                echo "Namespace name is required"
                 exit 1
             fi
-            shift
+            VIEW_UTILIZATION_NAMESPACE="$2";
+            shift 2
             ;;
-        l)
-            shift
-            if test $# -gt 0; then
-                VIEW_UTILIZATION_NODE_LABEL=$1
-            else
-                echo "no label specified"
+        -l|--selector)
+            if [[ $# -lt 2 ]]; then
+                echo "Label selector value is required"
                 exit 1
             fi
-            shift
+            VIEW_UTILIZATION_NODE_LABEL="$2";
+            shift 2
             ;;
-        o)
-            shift
-            if test $# -gt 0; then
-                if [[ "${1}" == "text" ]] || [[ "${1}" == "json" ]]; then
-                    VIEW_UTILIZATION_OUTPUT=$1
-                else
-                    echo "valid values are text, json"
-                    exit 1
-                fi
+        -o|--output)
+            if [ "${2}" == "text" ] || [ "${2}" == "json" ]; then
+                VIEW_UTILIZATION_OUTPUT="$2";
             else
-                echo "no output specified"
+                echo "Output value is required. Valid values are: text, json."
                 exit 1
             fi
+            shift 2
+            ;;
+        -h)
+            VIEW_UTILIZATION_UNITS="human";
             shift
             ;;
-
-        h)
-            VIEW_UTILIZATION_UNITS="human"
-            ;;
-        v)
+        -v)
             print_plugin_version
             ;;
-        *)
-            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
-                echo "Non-option argument: '-${OPTARG}'" >&2
-                print_help
+        --namespace=*)
+            if [ "${1#*=}" == "" ]; then
+                echo "Namespace name is required"
+                exit 1
             fi
+            VIEW_UTILIZATION_NAMESPACE="${1#*=}";
+            shift 1
+            ;;
+        --selector=*)
+            if [ "${1#*=}" == "" ]; then
+                echo "Label selector value is required"
+                exit 1
+            fi
+            VIEW_UTILIZATION_NODE_LABEL="${1#*=}";
+            shift 1
+            ;;
+        --output=*)
+            if [ "${1#*=}" == "text" ] || [ "${1#*=}" == "json" ]; then
+                VIEW_UTILIZATION_OUTPUT="${1#*=}";
+            else
+                echo "Output value is required. Valid values are: text, json."
+                exit 1
+            fi
+            shift 1
+            ;;
+        --help)
+            print_help
+            ;;
+        -*)
+            echo "Unknown option: $1" >&2;
+            exit 1
+            ;;
+        *)
+            echo "Unknown arument: $1" >&2;
+            exit 1
             ;;
     esac
 done
